:- module(validation_suite, [run_dynamic_suite/0]).
:- use_module(library(prolog_stack)).
:- use_module(scenario_manager).
:- use_module(data_validation).
:- use_module(report_generator).

:- chdir('../prolog').

:- dynamic test_passed/1, test_failed/3, test_case/4.

% --- Test Case Definitions ---
test_case('testsets/26usc469.pl', '26usc469', '26USC469', 1).
test_case('testsets/26usc469_real_estate_exemption.pl', '26usc469_real_estate_exemption', '26USC469_REAL_ESTATE_EXEMPTION', 2).
test_case('testsets/abstraction_boundary_overrun.pl', 'abstraction_boundary_overrun', 'ABSTRACTION_BOUNDARY_OVERRUN', 3).
test_case('testsets/abstraction_leakage.pl', 'abstraction_leakage', 'ABSTRACTION_LEAKAGE', 4).
test_case('testsets/academic_peer_review_gatekeeping.pl', 'academic_peer_review_gatekeeping', 'ACADEMIC_PEER_REVIEW_GATEKEEPING', 5).
test_case('testsets/academic_tenure_system.pl', 'academic_tenure_system', 'ACADEMIC_TENURE_SYSTEM', 6).
test_case('testsets/ad_fus_coordination.pl', 'ad_fus_coordination', 'AD_FUS_COORDINATION', 7).
test_case('testsets/ad_synaptic_deficit.pl', 'ad_synaptic_deficit', 'AD_SYNAPTIC_DEFICIT', 8).
test_case('testsets/adaptive_lag_trap.pl', 'adaptive_lag_trap', 'ADAPTIVE_LAG_TRAP', 9).
test_case('testsets/adversarial_surface_inflation.pl', 'adversarial_surface_inflation', 'ADVERSARIAL_SURFACE_INFLATION', 10).
test_case('testsets/adversarial_truth_decay.pl', 'adversarial_truth_decay', 'ADVERSARIAL_TRUTH_DECAY', 11).
test_case('testsets/adverse_possession.pl', 'adverse_possession_interval', 'ADVERSE_POSSESSION', 12).
test_case('testsets/advice_as_dangerous_gift.pl', 'advice_as_dangerous_gift', 'ADVICE_AS_DANGEROUS_GIFT', 13).
test_case('testsets/agency_atrophy.pl', 'agency_atrophy', 'AGENCY_ATROPHY', 14).
test_case('testsets/aging_well_assessment.pl', 'aging_longevity_tests', 'AGING_WELL_ASSESSMENT', 15).
test_case('testsets/ai_auditability_gap.pl', 'ai_auditability_gap', 'AI_AUDITABILITY_GAP', 16).
test_case('testsets/ai_cognitive_diversity_arbitrage.pl', 'ai_cognitive_diversity_arbitrage', 'AI_COGNITIVE_DIVERSITY_ARBITRAGE', 17).
test_case('testsets/ai_driven_surveillance_sensor_layer.pl', 'ai_driven_surveillance_sensor_layer', 'AI_DRIVEN_SURVEILLANCE_SENSOR_LAYER', 18).
test_case('testsets/ai_edu_decentralization.pl', 'ai_edu_decentralization', 'AI_EDU_DECENTRALIZATION', 19).
test_case('testsets/ai_evaluators_matching.pl', 'ai_evaluators_matching', 'AI_EVALUATORS_MATCHING', 20).
test_case('testsets/ai_professional_displacement.pl', 'ai_professional_displacement', 'AI_PROFESSIONAL_DISPLACEMENT', 21).
test_case('testsets/ai_task_horizon_reliability.pl', 'ai_task_horizon_reliability', 'AI_TASK_HORIZON_RELIABILITY', 22).
test_case('testsets/algorithmic_bias.pl', 'algorithmic_bias', 'ALGORITHMIC_BIAS', 23).
test_case('testsets/algorithmic_epistemic_capture.pl', 'algorithmic_epistemic_capture', 'ALGORITHMIC_EPISTEMIC_CAPTURE', 24).
test_case('testsets/alignment_tax_tradeoff.pl', 'alignment_tax_tradeoff', 'ALIGNMENT_TAX_TRADEOFF', 25).
test_case('testsets/alternative_sovereignty_scaffold.pl', 'alternative_sovereignty_scaffold', 'ALTERNATIVE_SOVEREIGNTY_SCAFFOLD', 26).
test_case('testsets/amish_technological_renunciation.pl', 'amish_technological_renunciation', 'AMISH_TECHNOLOGICAL_RENUNCIATION', 27).
test_case('testsets/ancestral_pueblo_hydrology.pl', 'ancestral_pueblo_hydrology', 'ANCESTRAL_PUEBLO_HYDROLOGY', 28).
test_case('testsets/ancient_grudge_verona.pl', 'ancient_grudge_verona', 'ANCIENT_GRUDGE_VERONA', 29).
test_case('testsets/anticipatory_capacity_failure.pl', 'anticipatory_capacity_failure', 'ANTICIPATORY_CAPACITY_FAILURE', 30).
test_case('testsets/antifragility.pl', 'antifragility', 'ANTIFRAGILITY', 31).
test_case('testsets/apartheid_nuclear_program.pl', 'apartheid_nuclear_program', 'APARTHEID_NUCLEAR_PROGRAM', 32).
test_case('testsets/arctic_geopolitical_flashpoint.pl', 'arctic_geopolitical_flashpoint', 'ARCTIC_GEOPOLITICAL_FLASHPOINT', 33).
test_case('testsets/arrows_impossibility_theorem.pl', 'arrows_era', 'ARROWS_IMPOSSIBILITY_THEOREM', 34).
test_case('testsets/artificial_scarcity_scaffold.pl', 'artificial_scarcity_scaffold', 'ARTIFICIAL_SCARCITY_SCAFFOLD', 35).
test_case('testsets/asce_7_22_seismic_design.pl', 'asce_cycle_22', 'ASCE_7_22_SEISMIC_DESIGN', 36).
test_case('testsets/asshole_filter_2015.pl', 'asshole_filter_2015', 'ASSHOLE_FILTER_2015', 37).
test_case('testsets/astm_d638_tensile_testing.pl', 'industrial_testing_regime', 'ASTM_D638_TENSILE_TESTING', 38).
test_case('testsets/asymmetric_burden_distribution.pl', 'asymmetric_burden_distribution', 'ASYMMETRIC_BURDEN_DISTRIBUTION', 39).
test_case('testsets/asymmetric_computational_difficulty.pl', 'asymmetric_computational_difficulty', 'ASYMMETRIC_COMPUTATIONAL_DIFFICULTY', 40).
test_case('testsets/atrophied_optimization_piton.pl', 'atrophied_optimization_piton', 'ATROPHIED_OPTIMIZATION_PITON', 41).
test_case('testsets/attention_as_bottleneck_resource.pl', 'attention_as_bottleneck_resource', 'ATTENTION_AS_BOTTLENECK_RESOURCE', 42).
test_case('testsets/attention_market_cannibalization.pl', 'attention_market_cannibalization', 'ATTENTION_MARKET_CANNIBALIZATION', 43).
test_case('testsets/authoritarian_power_paradox.pl', 'authoritarian_power_paradox', 'AUTHORITARIAN_POWER_PARADOX', 44).
test_case('testsets/automatic_enrollment_defaults.pl', 'automatic_enrollment_defaults', 'AUTOMATIC_ENROLLMENT_DEFAULTS', 45).
test_case('testsets/autonomous_toolchain_sprawl.pl', 'autonomous_toolchain_sprawl', 'AUTONOMOUS_TOOLCHAIN_SPRAWL', 46).
test_case('testsets/availability_heuristic.pl', 'availability_heuristic', 'AVAILABILITY_HEURISTIC', 47).
test_case('testsets/awareness_without_leverage.pl', 'awareness_without_leverage', 'AWARENESS_WITHOUT_LEVERAGE', 48).
test_case('testsets/axiom_of_choice_determinacy.pl', 'ac_era', 'AXIOM_OF_CHOICE_DETERMINACY', 49).
test_case('testsets/banach_fixed_point.pl', 'banach_era', 'BANACH_FIXED_POINT', 50).
test_case('testsets/banach_tarski_paradox.pl', 'banach_tarski_era', 'BANACH_TARSKI_PARADOX', 51).
test_case('testsets/bangladesh_july_national_charter.pl', 'bangladesh_july_national_charter', 'BANGLADESH_JULY_NATIONAL_CHARTER', 52).
test_case('testsets/bap_of_pigs_operational_silo.pl', 'operation_zapata_timeline', 'BAP_OF_PIGS_OPERATIONAL_SILO', 53).
test_case('testsets/base_pair_complementarity.pl', 'dna_structure_discovery', 'BASE_PAIR_COMPLEMENTARITY', 54).
test_case('testsets/basel_problem_convergence.pl', 'basel_era', 'BASEL_PROBLEM_CONVERGENCE', 55).
test_case('testsets/bedouin_sedentary_transition.pl', 'bedouin_sedentary_transition', 'BEDOUIN_SEDENTARY_TRANSITION', 56).
test_case('testsets/beief_argument_conclusion.pl', 'belief_argument_conclusion_interval', 'BEIEF_ARGUMENT_CONCLUSION', 57).
test_case('testsets/berkshire_compounding_culture.pl', 'berkshire_compounding_culture', 'BERKSHIRE_COMPOUNDING_CULTURE', 58).
test_case('testsets/big_data_astrophysics_arbitrage.pl', 'big_data_astrophysics_arbitrage', 'BIG_DATA_ASTROPHYSICS_ARBITRAGE', 59).
test_case('testsets/biological_curiosity.pl', 'biological_curiosity', 'BIOLOGICAL_CURIOSITY', 60).
test_case('testsets/bip_narrative_illusion.pl', 'bip_narrative_illusion_interval', 'BIP_NARRATIVE_ILLUSION', 61).
test_case('testsets/birthday_paradox_collison.pl', 'birthday_era', 'BIRTHDAY_PARADOX_COLLISON', 62).
test_case('testsets/blackstone_carried_interest_taxation.pl', 'blackstone_ipo_restructuring', 'BLACKSTONE_CARRIED_INTEREST_TAXATION', 63).
test_case('testsets/blackstone_conflicts_of_interest.pl', 'blackstone_conflict_era', 'BLACKSTONE_CONFLICTS_OF_INTEREST', 64).
test_case('testsets/blackstone_smd_control.pl', 'blackstone_smd_control', 'BLACKSTONE_SMD_CONTROL', 65).
test_case('testsets/blackstone_tax_receiveable_agreement.pl', 'blackstone_tra_life', 'BLACKSTONE_TAX_RECEIVEABLE_AGREEMENT', 66).
test_case('testsets/boundary_dissolution_risk.pl', 'boundary_dissolution_risk', 'BOUNDARY_DISSOLUTION_RISK', 67).
test_case('testsets/brain_network_paradigm_2026.pl', 'brain_network_paradigm_2026', 'BRAIN_NETWORK_PARADIGM_2026', 68).
test_case('testsets/brazil_2026_general_elections.pl', 'brazil_2026_general_elections', 'BRAZIL_2026_GENERAL_ELECTIONS', 69).
test_case('testsets/broke_vs_poor_grocery_math.pl', 'broke_vs_poor_grocery_math', 'BROKE_VS_POOR_GROCERY_MATH', 70).
test_case('testsets/brouwer_fixed_point.pl', 'brouwer_era', 'BROUWER_FIXED_POINT', 71).
test_case('testsets/buffons_needle_pi_estimation.pl', 'buffon_era', 'BUFFONS_NEEDLE_PI_ESTIMATION', 72).
test_case('testsets/burali_forte_paradox.pl', 'burali_forti_interval', 'BURALI_FORTE_PARADOX', 73).
test_case('testsets/burden_of_proof_engineering_safety.pl', 'challenger_launch_decision', 'BURDEN_OF_PROOF_ENGINEERING_SAFETY', 74).
test_case('testsets/burden_of_proof_legal_criminal.pl', 'criminal_trial_sequence', 'BURDEN_OF_PROOF_LEGAL_CRIMINAL', 75).
test_case('testsets/burden_of_proof_scientific_empirical.pl', 'scientific_revolution_current', 'BURDEN_OF_PROOF_SCIENTIFIC_EMPIRICAL', 76).
test_case('testsets/bureaucratic_legibility_collapse.pl', 'bureaucratic_legibility_collapse', 'BUREAUCRATIC_LEGIBILITY_COLLAPSE', 77).
test_case('testsets/bureaucratic_self_preservation.pl', 'bureaucratic_self_preservation', 'BUREAUCRATIC_SELF_PRESERVATION', 78).
test_case('testsets/bushman_money_magic.pl', 'bushman_money_magic_interval', 'BUSHMAN_MONEY_MAGIC', 79).
test_case('testsets/busy_beaver_noncomputability.pl', 'busy_beaver_era', 'BUSY_BEAVER_NONCOMPUTABILITY', 80).
test_case('testsets/cantor_set_topology.pl', 'cantor_set_topology', 'CANTOR_SET_TOPOLOGY', 81).
test_case('testsets/cap_theorem.pl', 'cap_theorem_interval', 'CAP_THEOREM', 82).
test_case('testsets/capability_eval_overhang.pl', 'capability_eval_overhang', 'CAPABILITY_EVAL_OVERHANG', 83).
test_case('testsets/capital_misallocation_spiral.pl', 'capital_misallocation_spiral', 'CAPITAL_MISALLOCATION_SPIRAL', 84).
test_case('testsets/carbon_credit_markets_2026.pl', 'carbon_credit_markets_2026_int', 'CARBON_CREDIT_MARKETS_2026', 85).
test_case('testsets/carrying_capacity.pl', 'carrying_capacity_interval', 'CARRYING_CAPACITY', 86).
test_case('testsets/cascading_constraint_failure.pl', 'cascading_constraint_failure', 'CASCADING_CONSTRAINT_FAILURE', 87).
test_case('testsets/castration_longevity_choice.pl', 'castration_longevity_choice', 'CASTRATION_LONGEVITY_CHOICE', 88).
test_case('testsets/cbdc_implementation.pl', 'cbdc_deployment', 'CBDC_IMPLEMENTATION', 89).
test_case('testsets/central_limit_theorem_convergence.pl', 'clt_era', 'CENTRAL_LIMIT_THEOREM_CONVERGENCE', 90).
test_case('testsets/chaitins_omega_undecidability.pl', 'chaitin_era', 'CHAITINS_OMEGA_UNDECIDABILITY', 91).
test_case('testsets/challenger_o_ring_integrity.pl', 'challenger_o_ring_integrity', 'CHALLENGER_O_RING_INTEGRITY', 92).
test_case('testsets/china_critical_mineral_chokepoint.pl', 'china_critical_mineral_chokepoint', 'CHINA_CRITICAL_MINERAL_CHOKEPOINT', 93).
test_case('testsets/china_taiwan_reunification_mandate.pl', 'rejuvenation_centenary_cycle', 'CHINA_TAIWAN_REUNIFICATION_MANDATE', 94).
test_case('testsets/choice_architecture_design.pl', 'rope_design', 'CHOICE_ARCHITECTURE_DESIGN', 95).
test_case('testsets/church_turing_thesis.pl', 'church_turing_era', 'CHURCH_TURING_THESIS', 96).
test_case('testsets/cia_fbi_legal_wall.pl', 'pre_911_silo_regime', 'CIA_FBI_LEGAL_WALL', 97).
test_case('testsets/cinderella_midnight_deadline.pl', 'midnight_deadline_period', 'CINDERELLA_MIDNIGHT_DEADLINE', 98).
test_case('testsets/circadian_decoupling_arbitrage.pl', 'circadian_decoupling_arbitrage', 'CIRCADIAN_DECOUPLING_ARBITRAGE', 99).
test_case('testsets/citation_collapse_dynamics.pl', 'citation_collapse_dynamics', 'CITATION_COLLAPSE_DYNAMICS', 100).
test_case('testsets/civilizational_maintenance_debt.pl', 'civilizational_maintenance_debt', 'CIVILIZATIONAL_MAINTENANCE_DEBT', 101).
test_case('testsets/click_chemistry_paradigm_2026.pl', 'click_chemistry_paradigm_2026', 'CLICK_CHEMISTRY_PARADIGM_2026', 102).
test_case('testsets/climate_attribution_2026.pl', 'climate_attribution_2026', 'CLIMATE_ATTRIBUTION_2026', 103).
test_case('testsets/climate_target_one_point_five.pl', 'climate_target_one_point_five', 'CLIMATE_TARGET_ONE_POINT_FIVE', 104).
test_case('testsets/cloudflare_dual_class_asymmetry.pl', 'cloudflare_dual_class_asymmetry', 'CLOUDFLARE_DUAL_CLASS_ASYMMETRY', 105).
test_case('testsets/cobra_effect.pl', 'cobra_effect', 'COBRA_EFFECT', 106).
test_case('testsets/cognitive_diversity_arbitrage.pl', 'cognitive_diversity_arbitrage', 'COGNITIVE_DIVERSITY_ARBITRAGE', 107).
test_case('testsets/cognitive_energy_budget.pl', 'cognitive_energy_budget', 'COGNITIVE_ENERGY_BUDGET', 108).
test_case('testsets/cognitive_induction_gap.pl', 'cognitive_induction_gap', 'COGNITIVE_INDUCTION_GAP', 109).
test_case('testsets/cognitive_mimicry_arbitrage.pl', 'cognitive_mimicry_arbitrage', 'COGNITIVE_MIMICRY_ARBITRAGE', 110).
test_case('testsets/cognitive_surrender_to_system_3.pl', 'system_3_emergence', 'COGNITIVE_SURRENDER_TO_SYSTEM_3', 111).
test_case('testsets/coinbase_crypto_volatility.pl', 'coinbase_ipo_window', 'COINBASE_CRYPTO_VOLATILITY', 112).
test_case('testsets/coinbase_regulatory_uncertainty.pl', 'coinbase_regulatory_uncertainty', 'COINBASE_REGULATORY_UNCERTAINTY', 113).
test_case('testsets/collatz_conjecture_determinism.pl', 'collatz_era', 'COLLATZ_CONJECTURE_DETERMINISM', 114).
test_case('testsets/collective_action_deadlock.pl', 'collective_action_deadlock', 'COLLECTIVE_ACTION_DEADLOCK', 115).
test_case('testsets/college_admissions_market.pl', 'college_admissions_market', 'COLLEGE_ADMISSIONS_MARKET', 116).
test_case('testsets/colorado_sbe_decentralization_friction.pl', 'colorado_sbe_decentralization_friction', 'COLORADO_SBE_DECENTRALIZATION_FRICTION', 117).
test_case('testsets/columbia_2026_elections.pl', 'colombia_2026_presidential_election', 'COLUMBIA_2026_ELECTIONS', 118).
test_case('testsets/comitatus_bond.pl', 'comitatus_era', 'COMITATUS_BOND', 119).
test_case('testsets/complexity_debt.pl', 'complexity_debt', 'COMPLEXITY_DEBT', 120).
test_case('testsets/compounding_logic.pl', 'compounding_logic', 'COMPOUNDING_LOGIC', 121).
test_case('testsets/confirmation_bias.pl', 'confirmation_bias_interval', 'CONFIRMATION_BIAS', 122).
test_case('testsets/consensus_without_truth.pl', 'consensus_without_truth', 'CONSENSUS_WITHOUT_TRUTH', 123).
test_case('testsets/constitutional_consecration.pl', 'gettysburg_address_analysis', 'CONSTITUTIONAL_CONSECRATION', 124).
test_case('testsets/constitutional_supremacy.pl', 'constitutional_supremacy', 'CONSTITUTIONAL_SUPREMACY', 125).
test_case('testsets/constraint_interaction_explosion.pl', 'constraint_interaction_explosion', 'CONSTRAINT_INTERACTION_EXPLOSION', 126).
test_case('testsets/container_capacity_mismatch.pl', 'container_capacity_mismatch', 'CONTAINER_CAPACITY_MISMATCH', 127).
test_case('testsets/continuum_hypothesis_undecidability.pl', 'continuum_era', 'CONTINUUM_HYPOTHESIS_UNDECIDABILITY', 128).
test_case('testsets/conversational_dogmas_interuption.pl', 'conversational_dogmas_interruption', 'CONVERSATIONAL_DOGMAS_INTERUPTION', 129).
test_case('testsets/conways_game_of_life_dynamics.pl', 'conway_era', 'CONWAYS_GAME_OF_LIFE_DYNAMICS', 130).
test_case('testsets/coordination_attack_vulnerability.pl', 'coordination_attack_vulnerability', 'COORDINATION_ATTACK_VULNERABILITY', 131).
test_case('testsets/coordination_fatigue.pl', 'coordination_fatigue', 'COORDINATION_FATIGUE', 132).
test_case('testsets/coordination_threshold_failure.pl', 'coordination_threshold_failure', 'COORDINATION_THRESHOLD_FAILURE', 133).
test_case('testsets/copyleft_viral_licensing.pl', 'copyleft_viral_licensing', 'COPYLEFT_VIRAL_LICENSING', 134).
test_case('testsets/copyright_protection.pl', 'copyright_protection', 'COPYRIGHT_PROTECTION', 135).
test_case('testsets/cost_of_observation.pl', 'evolutionary_pressure_01', 'COST_OF_OBSERVATION', 136).
test_case('testsets/countable_infinity_cardinality.pl', 'countable_infinity_cardinality', 'COUNTABLE_INFINITY_CARDINALITY', 137).
test_case('testsets/couples_residency_match.pl', 'couples_residency_match', 'COUPLES_RESIDENCY_MATCH', 138).
test_case('testsets/cow_field_poop.pl', 'cow_field_poop', 'COW_FIELD_POOP', 139).
test_case('testsets/creative_commons_licensing.pl', 'creative_commons_licensing', 'CREATIVE_COMMONS_LICENSING', 140).
test_case('testsets/credibility_inflation.pl', 'credibility_inflation', 'CREDIBILITY_INFLATION', 141).
test_case('testsets/crisis_signal_saturation.pl', 'crisis_signal_saturation', 'CRISIS_SIGNAL_SATURATION', 142).
test_case('testsets/crispr_genomic_rewrite_2026.pl', 'crispr_genomic_rewrite_2026', 'CRISPR_GENOMIC_REWRITE_2026', 143).
test_case('testsets/critical_actor_overcentralization.pl', 'critical_actor_overcentralization', 'CRITICAL_ACTOR_OVERCENTRALIZATION', 144).
test_case('testsets/cross_domain_coupling_spiral.pl', 'cross_domain_coupling_spiral', 'CROSS_DOMAIN_COUPLING_SPIRAL', 145).
test_case('testsets/cuba_mandatrophic_collapse.pl', 'cuba_blackout_cycle', 'CUBA_MANDATROPHIC_COLLAPSE', 146).
test_case('testsets/cuban_missile_crisis_excomm_delibration.pl', 'thirteen_days_crisis', 'CUBAN_MISSILE_CRISIS_EXCOMM_DELIBRATION', 147).
test_case('testsets/cultural_memory_decay.pl', 'cultural_memory_decay', 'CULTURAL_MEMORY_DECAY', 148).
test_case('testsets/currys_paradox.pl', 'currys_paradox_interval', 'CURRYS_PARADOX', 149).
test_case('testsets/damped_harmonics.pl', 'damped_harmonics', 'DAMPED_HARMONICS', 150).
test_case('testsets/dark_patterns_manipulation.pl', 'dark_patterns_manipulation', 'DARK_PATTERNS_MANIPULATION', 151).
test_case('testsets/data_laundering_pipeline.pl', 'data_laundering_pipeline', 'DATA_LAUNDERING_PIPELINE', 152).
test_case('testsets/dead_sea_effect.pl', 'dead_sea_effect', 'DEAD_SEA_EFFECT', 153).
test_case('testsets/decision_latency_mismatch.pl', 'decision_latency_mismatch', 'DECISION_LATENCY_MISMATCH', 154).
test_case('testsets/deferential_realism_core.pl', 'dr_recursive_int', 'DEFERENTIAL_REALISM_CORE', 155).
test_case('testsets/deferred_risk_realization.pl', 'deferred_risk_realization', 'DEFERRED_RISK_REALIZATION', 156).
test_case('testsets/delayed_feedback_instability.pl', 'delayed_feedback_instability', 'DELAYED_FEEDBACK_INSTABILITY', 157).
test_case('testsets/demographic_inertia_trap.pl', 'demographic_inertia_trap', 'DEMOGRAPHIC_INERTIA_TRAP', 158).
test_case('testsets/digital_credentialing_verification.pl', 'credentialing_shift_2026', 'DIGITAL_CREDENTIALING_VERIFICATION', 159).
test_case('testsets/digital_identity_tether.pl', 'digital_identity_tether', 'DIGITAL_IDENTITY_TETHER', 160).
test_case('testsets/dionysaic_frenzy.pl', 'dionysiac_frenzy_interval', 'DIONYSAIC_FRENZY', 161).
test_case('testsets/dldr_information_policy.pl', 'dldr_policy_interval', 'DLDR_INFORMATION_POLICY', 162).
test_case('testsets/dunbars_number.pl', 'dunbar_interval', 'DUNBARS_NUMBER', 163).
test_case('testsets/dunning_kruger_effect.pl', 'dunning_kruger_effect', 'DUNNING_KRUGER_EFFECT', 164).
test_case('testsets/e2ee_digital_privacy_2026.pl', 'e2ee_digital_privacy_2026', 'E2EE_DIGITAL_PRIVACY_2026', 165).
test_case('testsets/educational_unbundling_implementation.pl', 'implementation_window_2026', 'EDUCATIONAL_UNBUNDLING_IMPLEMENTATION', 166).
test_case('testsets/electrification_scale_2026.pl', 'electrification_scale_2026', 'ELECTRIFICATION_SCALE_2026', 167).
test_case('testsets/elencher_identity_transformation.pl', 'elencher_identity_transformation', 'ELENCHER_IDENTITY_TRANSFORMATION', 168).
test_case('testsets/elite_overproduction_instability.pl', 'elite_overproduction_instability', 'ELITE_OVERPRODUCTION_INSTABILITY', 169).
test_case('testsets/emergency_deployment_scaffold.pl', 'emergency_bridge_scaffold', 'EMERGENCY_DEPLOYMENT_SCAFFOLD', 170).
test_case('testsets/emergency_mode_lock_in.pl', 'emergency_mode_lock_in', 'EMERGENCY_MODE_LOCK_IN', 171).
test_case('testsets/emergency_oversight_bureau.pl', 'emergency_oversight_bureau', 'EMERGENCY_OVERSIGHT_BUREAU', 172).
test_case('testsets/emergency_powers_ratchet.pl', 'emergency_powers_ratchet', 'EMERGENCY_POWERS_RATCHET', 173).
test_case('testsets/emergent_goal_misalignment.pl', 'emergent_goal_misalignment', 'EMERGENT_GOAL_MISALIGNMENT', 174).
test_case('testsets/empty_tomb_transformation.pl', 'empty_tomb_transformation', 'EMPTY_TOMB_TRANSFORMATION', 175).
test_case('testsets/emrgency_medicine_clinical_guidelines.pl', 'em_practice_v2', 'EMRGENCY_MEDICINE_CLINICAL_GUIDELINES', 176).
test_case('testsets/endocrine_disruption_society.pl', 'endocrine_disruption_society', 'ENDOCRINE_DISRUPTION_SOCIETY', 177).
test_case('testsets/endowment_effect.pl', 'endowment_interval', 'ENDOWMENT_EFFECT', 178).
test_case('testsets/epigenetics_complexity_2026.pl', 'epigenetics_complexity_2026', 'EPIGENETICS_COMPLEXITY_2026', 179).
test_case('testsets/epistemic_free_rider_problem.pl', 'epistemic_free_rider_problem', 'EPISTEMIC_FREE_RIDER_PROBLEM', 180).
test_case('testsets/epistemic_overload_collapse.pl', 'epistemic_overload_collapse', 'EPISTEMIC_OVERLOAD_COLLAPSE', 181).
test_case('testsets/ergo_autolykos_asic_resistance.pl', 'ergo_autolykos_asic_resistance', 'ERGO_AUTOLYKOS_ASIC_RESISTANCE', 182).
test_case('testsets/ergo_dexy_gold_protocol.pl', 'dexy_gold_interval', 'ERGO_DEXY_GOLD_PROTOCOL', 183).
test_case('testsets/ergo_lets_protocol.pl', 'ergo_lets_interval', 'ERGO_LETS_PROTOCOL', 184).
test_case('testsets/ergo_mixer_protocol.pl', 'ergo_mixer_protocol', 'ERGO_MIXER_PROTOCOL', 185).
test_case('testsets/ergo_nipopows.pl', 'ergo_nipopows', 'ERGO_NIPOPOWS', 186).
test_case('testsets/ergo_rosen_bridge_protocol.pl', 'rosen_bridge_interval', 'ERGO_ROSEN_BRIDGE_PROTOCOL', 187).
test_case('testsets/ergo_sig_usd_protocol.pl', 'sig_usd_interval', 'ERGO_SIG_USD_PROTOCOL', 188).
test_case('testsets/ergo_storage_rent.pl', 'ergo_storage_rent', 'ERGO_STORAGE_RENT', 189).
test_case('testsets/ergo_storage_rent_mechanism.pl', 'ergo_storage_rent_mechanism', 'ERGO_STORAGE_RENT_MECHANISM', 190).
test_case('testsets/ergodic_theorems.pl', 'ergodic_interval', 'ERGODIC_THEOREMS', 191).
test_case('testsets/ergot_grain_poisoning.pl', 'ergot_grain_poisoning_interval', 'ERGOT_GRAIN_POISONING', 192).
test_case('testsets/euler_characteristic_topology.pl', 'euler_era', 'EULER_CHARACTERISTIC_TOPOLOGY', 193).
test_case('testsets/evidence_half_life.pl', 'evidence_half_life', 'EVIDENCE_HALF_LIFE', 194).
test_case('testsets/evolutionary_knowledge.pl', 'evolutionary_knowledge', 'EVOLUTIONARY_KNOWLEDGE', 195).
test_case('testsets/evolutionary_mismatch_load.pl', 'evolutionary_mismatch_load', 'EVOLUTIONARY_MISMATCH_LOAD', 196).
test_case('testsets/exoplanet_habitability_arbitrage.pl', 'exoplanetary_habitability_arbitrage', 'EXOPLANET_HABITABILITY_ARBITRAGE', 197).
test_case('testsets/expert_disempowerment.pl', 'expert_disempowerment', 'EXPERT_DISEMPOWERMENT', 198).
test_case('testsets/exploration_vs_exploitation.pl', 'exploration_vs_exploitation', 'EXPLORATION_VS_EXPLOITATION', 199).
test_case('testsets/extraordinary_narrative_shift.pl', 'extraordinary_narrative_shift', 'EXTRAORDINARY_NARRATIVE_SHIFT', 200).
test_case('testsets/factional_instability.pl', 'federalist_10_analysis', 'FACTIONAL_INSTABILITY', 201).
test_case('testsets/faint_blue_neural_bifurcation.pl', 'faint_blue_neural_bifurcation', 'FAINT_BLUE_NEURAL_BIFURCATION', 202).
test_case('testsets/fair_use_doctrine.pl', 'fair_use_doctrine', 'FAIR_USE_DOCTRINE', 203).
test_case('testsets/family_estrangement_ratio.pl', 'family_estrangement_ratio', 'FAMILY_ESTRANGEMENT_RATIO', 204).
test_case('testsets/family_succession_and_decadence.pl', 'atsumono_period', 'FAMILY_SUCCESSION_AND_DECADENCE', 205).
test_case('testsets/fast_growing_hierarchy.pl', 'fast_growing_hierarchy', 'FAST_GROWING_HIERARCHY', 206).
test_case('testsets/feedback_loop_desynchronization.pl', 'feedback_loop_desynchronization', 'FEEDBACK_LOOP_DESYNCHRONIZATION', 207).
test_case('testsets/feigenbaum_universality.pl', 'feigenbaum_universality', 'FEIGENBAUM_UNIVERSALITY', 208).
test_case('testsets/financialization_drag.pl', 'financial_drag', 'FINANCIALIZATION_DRAG', 209).
test_case('testsets/finite_pool_of_worry.pl', 'finite_pool_of_worry_interval', 'FINITE_POOL_OF_WORRY', 210).
test_case('testsets/finite_simple_groups_classification.pl', 'cfsg_era', 'FINITE_SIMPLE_GROUPS_CLASSIFICATION', 211).
test_case('testsets/fiscal_dominance_trap.pl', 'fiscal_dominance_trap', 'FISCAL_DOMINANCE_TRAP', 212).
test_case('testsets/fittss_law.pl', 'fittss_law_interval', 'FITTSS_LAW', 213).
test_case('testsets/fmeca_procedures_1980.pl', 'fmeca_standard_era', 'FMECA_PROCEDURES_1980', 214).
test_case('testsets/four_color_theorem_topological_bound.pl', 'four_color_era', 'FOUR_COLOR_THEOREM_TOPOLOGICAL_BOUND', 215).
test_case('testsets/fragile_middle_layer_collapse.pl', 'fragile_middle_layer_collapse', 'FRAGILE_MIDDLE_LAYER_COLLAPSE', 216).
test_case('testsets/framing_effect.pl', 'framing_effect_interval', 'FRAMING_EFFECT', 217).
test_case('testsets/france_2027_presidential_election.pl', 'france_2027_presidential_election', 'FRANCE_2027_PRESIDENTIAL_ELECTION', 218).
test_case('testsets/france_cordon_sanitaire_2026.pl', 'france_cordon_sanitaire_2026', 'FRANCE_CORDON_SANITAIRE_2026', 219).
test_case('testsets/frankenstein_creation_hubris.pl', 'frankenstein_creation_hubris', 'FRANKENSTEIN_CREATION_HUBRIS', 220).
test_case('testsets/french_local_elections_march_2026.pl', 'france_local_elections_march_2026', 'FRENCH_LOCAL_ELECTIONS_MARCH_2026', 221).
test_case('testsets/fundamental_theorem_of_algebra.pl', 'fta_era', 'FUNDAMENTAL_THEOREM_OF_ALGEBRA', 222).
test_case('testsets/gale_shapley.pl', 'gale_shapley', 'GALE_SHAPLEY', 223).
test_case('testsets/galois_theory_symmetry.pl', 'galois_era', 'GALOIS_THEORY_SYMMETRY', 224).
test_case('testsets/gamblers_ruin_stochastic_extinction.pl', 'ruin_era', 'GAMBLERS_RUIN_STOCHASTIC_EXTINCTION', 225).
test_case('testsets/gauss_bonnet_topology.pl', 'gauss_bonnet_era', 'GAUSS_BONNET_TOPOLOGY', 226).
test_case('testsets/generational_replacement_inertia.pl', 'generational_replacement_inertia', 'GENERATIONAL_REPLACEMENT_INERTIA', 227).
test_case('testsets/genetic_algorithms_evolution.pl', 'genetic_algorithms_evolution', 'GENETIC_ALGORITHMS_EVOLUTION', 228).
test_case('testsets/genetic_predisposition.pl', 'genetic_predisposition_interval', 'GENETIC_PREDISPOSITION', 229).
test_case('testsets/germline_regulation_threshold_2026.pl', 'germline_regulation_threshold_2026', 'GERMLINE_REGULATION_THRESHOLD_2026', 230).
test_case('testsets/gig_economy_algorithmic_managment.pl', 'platform_labor_epoch', 'GIG_ECONOMY_ALGORITHMIC_MANAGMENT', 231).
test_case('testsets/gilgamesh_mortality_limit.pl', 'gilgamesh_epic_cycle', 'GILGAMESH_MORTALITY_LIMIT', 232).
test_case('testsets/gita_kurukshetra.pl', 'gita_kurukshetra', 'GITA_KURUKSHETRA', 233).
test_case('testsets/global_protocol_entrenchment.pl', 'global_protocol_entrenchment', 'GLOBAL_PROTOCOL_ENTRENCHMENT', 234).
test_case('testsets/global_stimulus_spree.pl', 'global_stimulus_spree', 'GLOBAL_STIMULUS_SPREE', 235).
test_case('testsets/global_water_bankruptcy.pl', 'global_water_bankruptcy', 'GLOBAL_WATER_BANKRUPTCY', 236).
test_case('testsets/glp1_payload_efficiency_pivot.pl', 'glp1_market_impact_2026', 'GLP1_PAYLOAD_EFFICIENCY_PIVOT', 237).
test_case('testsets/goal_boundary_poisoning.pl', 'goal_boundary_poisoning', 'GOAL_BOUNDARY_POISONING', 238).
test_case('testsets/godels_incompleteness_theorems.pl', 'goedel_era', 'GODELS_INCOMPLETENESS_THEOREMS', 239).
test_case('testsets/goldbach_conjecture.pl', 'goldbach_era', 'GOLDBACH_CONJECTURE', 240).
test_case('testsets/golden_handcuffs.pl', 'golden_handcuffs', 'GOLDEN_HANDCUFFS', 241).
test_case('testsets/goodharts_law.pl', 'goodharts_law_interval', 'GOODHARTS_LAW', 242).
test_case('testsets/governance_latency_gap.pl', 'governance_latency_gap', 'GOVERNANCE_LATENCY_GAP', 243).
test_case('testsets/governance_overfitting.pl', 'governance_overfitting', 'GOVERNANCE_OVERFITTING', 244).
test_case('testsets/gradient_descent_optimization.pl', 'gradient_descent_optimization', 'GRADIENT_DESCENT_OPTIMIZATION', 245).
test_case('testsets/graph_coloring_complexity.pl', 'graph_coloring_interval', 'GRAPH_COLORING_COMPLEXITY', 246).
test_case('testsets/greenland_seizure_trade_war.pl', 'greenland_crisis_2026', 'GREENLAND_SEIZURE_TRADE_WAR', 247).
test_case('testsets/greshams_law.pl', 'greshams_law', 'GRESHAMS_LAW', 248).
test_case('testsets/grete_samsa_transition.pl', 'grete_samsa_transition', 'GRETE_SAMSA_TRANSITION', 249).
test_case('testsets/grievance_stack_overflow.pl', 'grievance_stack_overflow', 'GRIEVANCE_STACK_OVERFLOW', 250).
test_case('testsets/gs1_gln_identification.pl', 'gln_standard_lifecycle', 'GS1_GLN_IDENTIFICATION', 251).
test_case('testsets/gs1_standardized_identification.pl', 'gs1_spec_v25', 'GS1_STANDARDIZED_IDENTIFICATION', 252).
test_case('testsets/halting_problem_undecidability.pl', 'halting_era', 'HALTING_PROBLEM_UNDECIDABILITY', 253).
test_case('testsets/hamiltonian_path_complexity.pl', 'hamiltonian_path_complexity', 'HAMILTONIAN_PATH_COMPLEXITY', 254).
test_case('testsets/hammurabi.pl', 'hammurabi_lex_talionis', 'HAMMURABI', 255).
test_case('testsets/hanlons_razor.pl', 'hanlons_razor', 'HANLONS_RAZOR', 256).
test_case('testsets/happiness_of_others.pl', 'happiness_of_others', 'HAPPINESS_OF_OTHERS', 257).
test_case('testsets/harm_principle_liberty.pl', 'on_liberty_analysis', 'HARM_PRINCIPLE_LIBERTY', 258).
test_case('testsets/harry_potter_liberalism.pl', 'hp_liberalism', 'HARRY_POTTER_LIBERALISM', 259).
test_case('testsets/hawthorne_effect.pl', 'hawthorne_interval', 'HAWTHORNE_EFFECT', 260).
test_case('testsets/hedonic_adaptation_baseline.pl', 'hedonic_adaptation_baseline', 'HEDONIC_ADAPTATION_BASELINE', 261).
test_case('testsets/heisenberg_uncertainty.pl', 'heisenberg_interval', 'HEISENBERG_UNCERTAINTY', 262).
test_case('testsets/helsinki_bus_theory.pl', 'helsinki_bus_theory', 'HELSINKI_BUS_THEORY', 263).
test_case('testsets/heuristic_optimization.pl', 'heuristic_optimization', 'HEURISTIC_OPTIMIZATION', 264).
test_case('testsets/hidden_interdependency_risk.pl', 'hidden_interdependency_risk', 'HIDDEN_INTERDEPENDENCY_RISK', 265).
test_case('testsets/hilberts_hotel_infinity.pl', 'hilberts_hotel_infinity', 'HILBERTS_HOTEL_INFINITY', 266).
test_case('testsets/hiv_prep_prevention_2026.pl', 'hiv_prep_prevention_2026', 'HIV_PREP_PREVENTION_2026', 267).
test_case('testsets/hoa_covenants.pl', 'hoa_interval', 'HOA_COVENANTS', 268).
test_case('testsets/hollow_state_syndrome.pl', 'hollow_state_syndrome', 'HOLLOW_STATE_SYNDROME', 269).
test_case('testsets/hominin_evolutionary_bottleneck.pl', 'hominin_evolutionary_bottleneck', 'HOMININ_EVOLUTIONARY_BOTTLENECK', 270).
test_case('testsets/hu_2026_electoral_parity.pl', 'hu_2026_election_rules', 'HU_2026_ELECTORAL_PARITY', 271).
test_case('testsets/hydra_game.pl', 'hydra_interval', 'HYDRA_GAME', 272).
test_case('testsets/hypercompression_of_time_horizons.pl', 'milliseconds', 'HYPERCOMPRESSION_OF_TIME_HORIZONS', 273).
test_case('testsets/hypernormie_equilibrium.pl', 'hypernormie_equilibrium', 'HYPERNORMIE_EQUILIBRIUM', 274).
test_case('testsets/identity_stack_incompatibility.pl', 'identity_stack_incompatibility', 'IDENTITY_STACK_INCOMPATIBILITY', 275).
test_case('testsets/incentive_surface_warping.pl', 'incentive_surface_warping', 'INCENTIVE_SURFACE_WARPING', 276).
test_case('testsets/indexical_relativity_core.pl', 'meta_logic_01', 'INDEXICAL_RELATIVITY_CORE', 277).
test_case('testsets/individual_revolution_autonomy.pl', 'individual_revolution_autonomy', 'INDIVIDUAL_REVOLUTION_AUTONOMY', 278).
test_case('testsets/inference_cost_scaling_law.pl', 'inference_cost_scaling_law', 'INFERENCE_COST_SCALING_LAW', 279).
test_case('testsets/information_foraging_theory.pl', 'information_foraging_theory', 'INFORMATION_FORAGING_THEORY', 280).
test_case('testsets/infrastructure_decay_piton.pl', 'infrastructure_decay_piton', 'INFRASTRUCTURE_DECAY_PITON', 281).
test_case('testsets/infrastructure_interoperability_decay.pl', 'infrastructure_interoperability_decay', 'INFRASTRUCTURE_INTEROPERABILITY_DECAY', 282).
test_case('testsets/inner_model_theory_constraints.pl', 'inner_model_era', 'INNER_MODEL_THEORY_CONSTRAINTS', 283).
test_case('testsets/innovators_dilemma.pl', 'innovators_dilemma_interval', 'INNOVATORS_DILEMMA', 284).
test_case('testsets/institutional_inertia_lock.pl', 'institutional_inertia_lock', 'INSTITUTIONAL_INERTIA_LOCK', 285).
test_case('testsets/institutional_memory_loss.pl', 'institutional_memory_loss', 'INSTITUTIONAL_MEMORY_LOSS', 286).
test_case('testsets/institutional_mutation_domestication.pl', 'institutional_mutation_domestication', 'INSTITUTIONAL_MUTATION_DOMESTICATION', 287).
test_case('testsets/institutional_mutation_without_selection.pl', 'institutional_mutation_without_selection', 'INSTITUTIONAL_MUTATION_WITHOUT_SELECTION', 288).
test_case('testsets/institutional_trust_decay.pl', 'institutional_trust_decay', 'INSTITUTIONAL_TRUST_DECAY', 289).
test_case('testsets/insult_wisdom_training.pl', 'insult_wisdom_interval', 'INSULT_WISDOM_TRAINING', 290).
test_case('testsets/integrated_digital_governance_stack.pl', 'meta_stack_convergence', 'INTEGRATED_DIGITAL_GOVERNANCE_STACK', 291).
test_case('testsets/interface_contract_breakdown.pl', 'interface_contract_breakdown', 'INTERFACE_CONTRACT_BREAKDOWN', 292).
test_case('testsets/internet_archive_preservation.pl', 'ia_digital_preservation', 'INTERNET_ARCHIVE_PRESERVATION', 293).
test_case('testsets/interpretive_frame_fragmentation.pl', 'interpretive_frame_fragmentation', 'INTERPRETIVE_FRAME_FRAGMENTATION', 294).
test_case('testsets/intertemporal_responsibility_gap.pl', 'intertemporal_responsibility_gap', 'INTERTEMPORAL_RESPONSIBILITY_GAP', 295).
test_case('testsets/invisible_infrastructure_dependency.pl', 'invisible_infrastructure_dependency', 'INVISIBLE_INFRASTRUCTURE_DEPENDENCY', 296).
test_case('testsets/iran_mandatrophic_collapse.pl', 'iran_unrest_2025', 'IRAN_MANDATROPHIC_COLLAPSE', 297).
test_case('testsets/iron_law_of_oligarchy.pl', 'oligarchy_interval', 'IRON_LAW_OF_OLIGARCHY', 298).
test_case('testsets/irreversible_policy_commitment.pl', 'irreversible_policy_commitment', 'IRREVERSIBLE_POLICY_COMMITMENT', 299).
test_case('testsets/isa_education_scaffold.pl', 'isa_education_scaffold', 'ISA_EDUCATION_SCAFFOLD', 300).
test_case('testsets/israel_electoral_threshold.pl', 'israel_electoral_threshold', 'ISRAEL_ELECTORAL_THRESHOLD', 301).
test_case('testsets/israel_norwegian_law.pl', 'israel_norwegian_law', 'ISRAEL_NORWEGIAN_LAW', 302).
test_case('testsets/israel_override_clause.pl', 'israel_override_clause', 'ISRAEL_OVERRIDE_CLAUSE', 303).
test_case('testsets/israel_surplus_vote_agreements.pl', 'israel_surplus_vote_agreements', 'ISRAEL_SURPLUS_VOTE_AGREEMENTS', 304).
test_case('testsets/japanese_energy_scaffold_2025.pl', 'japan_gx_transition', 'JAPANESE_ENERGY_SCAFFOLD_2025', 305).
test_case('testsets/jevons_paradox.pl', 'jevons_interval', 'JEVONS_PARADOX', 306).
test_case('testsets/job_hunt_volume_system_2026.pl', 'job_hunt_volume_system_2026', 'JOB_HUNT_VOLUME_SYSTEM_2026', 307).
test_case('testsets/keltner_relationship_evaluation.pl', 'keltner_relationship_evaluation', 'KELTNER_RELATIONSHIP_EVALUATION', 308).
test_case('testsets/khantivadin_radical_patience.pl', 'khantivadin_patience_interval', 'KHANTIVADIN_RADICAL_PATIENCE', 309).
test_case('testsets/kidney_exchange_market.pl', 'kidney_exchange_market', 'KIDNEY_EXCHANGE_MARKET', 310).
test_case('testsets/kirby_paris_theorem.pl', 'kirby_paris_interval', 'KIRBY_PARIS_THEOREM', 311).
test_case('testsets/kjv_great_awakening.pl', 'kjv_great_awakening', 'KJV_GREAT_AWAKENING', 312).
test_case('testsets/kjv_linguistic_residue.pl', 'kjv_linguistic_residue', 'KJV_LINGUISTIC_RESIDUE', 313).
test_case('testsets/kjv_puritan_new_world_exit.pl', 'kjv_puritan_new_world_exit', 'KJV_PURITAN_NEW_WORLD_EXIT', 314).
test_case('testsets/kjv_textual_authority.pl', 'kjv_textual_authority', 'KJV_TEXTUAL_AUTHORITY', 315).
test_case('testsets/kleene_recursion_theorem.pl', 'kleene_era', 'KLEENE_RECURSION_THEOREM', 316).
test_case('testsets/knowledge_action_gap.pl', 'knowledge_action_gap', 'KNOWLEDGE_ACTION_GAP', 317).
test_case('testsets/landscape_of_fear_2026.pl', 'landscape_of_fear_2026', 'LANDSCAPE_OF_FEAR_2026', 318).
test_case('testsets/large_cardinals_foundations.pl', 'large_cardinal_era', 'LARGE_CARDINALS_FOUNDATIONS', 319).
test_case('testsets/latent_goal_activation.pl', 'latent_goal_activation', 'LATENT_GOAL_ACTIVATION', 320).
test_case('testsets/latent_regulatory_bomb.pl', 'latent_regulatory_bomb', 'LATENT_REGULATORY_BOMB', 321).
test_case('testsets/law_of_diminishing_returns.pl', 'diminishing_returns_interval', 'LAW_OF_DIMINISHING_RETURNS', 322).
test_case('testsets/layered_brain_processing.pl', 'layered_brain_processing', 'LAYERED_BRAIN_PROCESSING', 323).
test_case('testsets/legacy_system_technical_debt.pl', 'software_lifecycle_r7', 'LEGACY_SYSTEM_TECHNICAL_DEBT', 324).
test_case('testsets/legal_formalism_overhang.pl', 'legal_formalism_overhang', 'LEGAL_FORMALISM_OVERHANG', 325).
test_case('testsets/legibility_trap.pl', 'legibility_trap', 'LEGIBILITY_TRAP', 326).
test_case('testsets/legitimacy_without_capacity.pl', 'legitimacy_without_capacity', 'LEGITIMACY_WITHOUT_CAPACITY', 327).
test_case('testsets/legitimacy_without_effectiveness.pl', 'legitimacy_without_effectiveness', 'LEGITIMACY_WITHOUT_EFFECTIVENESS', 328).
test_case('testsets/lehman_repo_105.pl', 'lehman_repo_105', 'LEHMAN_REPO_105', 329).
test_case('testsets/liar_paradox.pl', 'liar_paradox_interval', 'LIAR_PARADOX', 330).
test_case('testsets/lindy_effect.pl', 'lindy_effect', 'LINDY_EFFECT', 331).
test_case('testsets/liquidity_illusion.pl', 'liquidity_illusion', 'LIQUIDITY_ILLUSION', 332).
test_case('testsets/litany_of_the_real.pl', 'litany_of_the_real', 'LITANY_OF_THE_REAL', 333).
test_case('testsets/lln_convergence.pl', 'lln_era', 'LLN_CONVERGENCE', 334).
test_case('testsets/lobs_theorem.pl', 'lobs_theorem_interval', 'LOBS_THEOREM', 335).
test_case('testsets/local_vs_global_optima.pl', 'local_vs_global_optima', 'LOCAL_VS_GLOBAL_OPTIMA', 336).
test_case('testsets/logistic_map_dynamics.pl', 'logistic_map_era', 'LOGISTIC_MAP_DYNAMICS', 337).
test_case('testsets/lorenz_attractor_dynamics.pl', 'lorenz_era', 'LORENZ_ATTRACTOR_DYNAMICS', 338).
test_case('testsets/lowenheim_skolem_theorem.pl', 'lowenheim_skolem_interval', 'LOWENHEIM_SKOLEM_THEOREM', 339).
test_case('testsets/lsd_microdosing_professional_openness.pl', 'lsd_microdosing_professional_openness', 'LSD_MICRODOSING_PROFESSIONAL_OPENNESS', 340).
test_case('testsets/lula_hemisphere_2026.pl', 'lula_hemisphere_2026', 'LULA_HEMISPHERE_2026', 341).
test_case('testsets/magna_carta_liberties.pl', 'magna_carta_liberties', 'MAGNA_CARTA_LIBERTIES', 342).
test_case('testsets/maintenance_capacity_shortfall.pl', 'maintenance_capacity_shortfall', 'MAINTENANCE_CAPACITY_SHORTFALL', 343).
test_case('testsets/maladaptive_selection_process.pl', 'maladaptive_selection_process', 'MALADAPTIVE_SELECTION_PROCESS', 344).
test_case('testsets/mandatrophic_margin_collapse.pl', 'mandatrophy_cycle', 'MANDATROPHIC_MARGIN_COLLAPSE', 345).
test_case('testsets/mandatrophic_margin_collapse_diagnostic.pl', 'mandatrophy_lifecycle', 'MANDATROPHIC_MARGIN_COLLAPSE_DIAGNOSTIC', 346).
test_case('testsets/marriage_problem.pl', 'optimal_stopping_marriage', 'MARRIAGE_PROBLEM', 347).
test_case('testsets/mars_rovers_navigational_autonomy.pl', 'mars_autonomy_evolution', 'MARS_ROVERS_NAVIGATIONAL_AUTONOMY', 348).
test_case('testsets/martian_signal_latency.pl', 'mariner_to_msl_era', 'MARTIAN_SIGNAL_LATENCY', 349).
test_case('testsets/matching_markets_general.pl', 'matching_markets_general', 'MATCHING_MARKETS_GENERAL', 350).
test_case('testsets/material_tensile_strength.pl', 'tensile_strength_interval', 'MATERIAL_TENSILE_STRENGTH', 351).
test_case('testsets/max_flow.pl', 'max_flow_min_cut', 'MAX_FLOW', 352).
test_case('testsets/mco_unit_system_discontinuity.pl', 'mco_failure_trajectory', 'MCO_UNIT_SYSTEM_DISCONTINUITY', 353).
test_case('testsets/med_diet_consensus_2026.pl', 'med_diet_consensus_2026', 'MED_DIET_CONSENSUS_2026', 354).
test_case('testsets/medical_residency_match.pl', 'medical_residency_match', 'MEDICAL_RESIDENCY_MATCH', 355).
test_case('testsets/medieval_church_hegomony.pl', 'medieval_church_hegemony', 'MEDIEVAL_CHURCH_HEGOMONY', 356).
test_case('testsets/memetic_fitness_vs_truth.pl', 'memetic_fitness_vs_truth', 'MEMETIC_FITNESS_VS_TRUTH', 357).
test_case('testsets/meta_governance_overload.pl', 'meta_governance_overload', 'META_GOVERNANCE_OVERLOAD', 358).
test_case('testsets/meta_model_lock_in.pl', 'meta_model_lock_in', 'META_MODEL_LOCK_IN', 359).
test_case('testsets/metabolic_constraint_cognition.pl', 'metabolic_constraint_cognition', 'METABOLIC_CONSTRAINT_COGNITION', 360).
test_case('testsets/metamorphosis_samsa.pl', 'samsa_transformation_period', 'METAMORPHOSIS_SAMSA', 361).
test_case('testsets/micro_robot_electronics_integration.pl', 'ek_robot_integration_cycle', 'MICRO_ROBOT_ELECTRONICS_INTEGRATION', 362).
test_case('testsets/microbiome_symbiosis.pl', 'microbiome_symbiosis', 'MICROBIOME_SYMBIOSIS', 363).
test_case('testsets/mil_std_461g_emi_control.pl', 'mil_std_461g_era', 'MIL_STD_461G_EMI_CONTROL', 364).
test_case('testsets/mil_std_810f_tailoring.pl', 'mil_std_810f_era', 'MIL_STD_810F_TAILORING', 365).
test_case('testsets/minimax_decision_rule.pl', 'minimax_era', 'MINIMAX_DECISION_RULE', 366).
test_case('testsets/mirror_of_erised_expectation.pl', 'erised_expectation', 'MIRROR_OF_ERISED_EXPECTATION', 367).
test_case('testsets/misunderstanding_as_mismatch.pl', 'misunderstanding_as_mismatch', 'MISUNDERSTANDING_AS_MISMATCH', 368).
test_case('testsets/model_autonomy_creep.pl', 'model_autonomy_creep', 'MODEL_AUTONOMY_CREEP', 369).
test_case('testsets/model_collapse_feedback_loop.pl', 'model_collapse_feedback_loop', 'MODEL_COLLAPSE_FEEDBACK_LOOP', 370).
test_case('testsets/model_of_models_regression.pl', 'model_of_models_regression', 'MODEL_OF_MODELS_REGRESSION', 371).
test_case('testsets/monetary_regime_transition.pl', 'nixon_shock_1971', 'MONETARY_REGIME_TRANSITION', 372).
test_case('testsets/monty_hall_conditional_probability.pl', 'probability_paradox_era', 'MONTY_HALL_CONDITIONAL_PROBABILITY', 373).
test_case('testsets/moores_law.pl', 'moores_law_interval', 'MOORES_LAW', 374).
test_case('testsets/moral_outsourcing.pl', 'moral_outsourcing', 'MORAL_OUTSOURCING', 375).
test_case('testsets/multi_agent_reward_hacking.pl', 'multi_agent_reward_hacking', 'MULTI_AGENT_REWARD_HACKING', 376).
test_case('testsets/multi_planetary_latency_lock.pl', 'multi_planetary_latency_lock', 'MULTI_PLANETARY_LATENCY_LOCK', 377).
test_case('testsets/mutual_defection_equilibrium.pl', 'mutual_defection_equilibrium', 'MUTUAL_DEFECTION_EQUILIBRIUM', 378).
test_case('testsets/naming_as_control.pl', 'naming_as_control', 'NAMING_AS_CONTROL', 379).
test_case('testsets/narrative_capacity_exhaustion.pl', 'narrative_capacity_exhaustion', 'NARRATIVE_CAPACITY_EXHAUSTION', 380).
test_case('testsets/narrative_overfitting.pl', 'narrative_overfitting', 'NARRATIVE_OVERFITTING', 381).
test_case('testsets/nasa_faster_better_cheaper.pl', 'fbc_era_operations', 'NASA_FASTER_BETTER_CHEAPER', 382).
test_case('testsets/nash_equilibrium_coordination.pl', 'nash_era', 'NASH_EQUILIBRIUM_COORDINATION', 383).
test_case('testsets/necessary_day_job.pl', 'necessary_day_job', 'NECESSARY_DAY_JOB', 384).
test_case('testsets/negative_emissions_arbitrage.pl', 'negative_emissions_arbitrage', 'NEGATIVE_EMISSIONS_ARBITRAGE', 385).
test_case('testsets/net_zero_stabilization.pl', 'net_zero_stabilization', 'NET_ZERO_STABILIZATION', 386).
test_case('testsets/network_effects.pl', 'network_effects', 'NETWORK_EFFECTS', 387).
test_case('testsets/neural_interoperability.pl', 'neural_interoperability', 'NEURAL_INTEROPERABILITY', 388).
test_case('testsets/neurodiversity_spectrum.pl', 'neurodiversity_spectrum', 'NEURODIVERSITY_SPECTRUM', 389).
test_case('testsets/neuroplasticity_plateau.pl', 'neuroplasticity_plateau', 'NEUROPLASTICITY_PLATEAU', 390).
test_case('testsets/new_civilizational_rope.pl', 'decentralized_infrastructure_rope', 'NEW_CIVILIZATIONAL_ROPE', 391).
test_case('testsets/newtons_method_convergence.pl', 'newton_era', 'NEWTONS_METHOD_CONVERGENCE', 392).
test_case('testsets/nine_day_buffer.pl', 'nine_day_buffer', 'NINE_DAY_BUFFER', 393).
test_case('testsets/no_cloning_theorem.pl', 'no_cloning_interval', 'NO_CLONING_THEOREM', 394).
test_case('testsets/noethers_theorem_symmetry.pl', 'noether_era', 'NOETHERS_THEOREM_SYMMETRY', 395).
test_case('testsets/non_compete_agreements.pl', 'non_compete_agreements', 'NON_COMPETE_AGREEMENTS', 396).
test_case('testsets/nonstandard_arithmetic_models.pl', 'skolem_era', 'NONSTANDARD_ARITHMETIC_MODELS', 397).
test_case('testsets/norm_erosion_threshold.pl', 'norm_erosion_threshold', 'NORM_EROSION_THRESHOLD', 398).
test_case('testsets/north_korea_songun_mandatrophy.pl', 'dprk_songun_cycle', 'NORTH_KOREA_SONGUN_MANDATROPHY', 399).
test_case('testsets/notary_ink_dependency.pl', 'notary_ink_dependency', 'NOTARY_INK_DEPENDENCY', 400).
test_case('testsets/omelet_perfection_complexity.pl', 'omelet_perfection_interval', 'OMELET_PERFECTION_COMPLEXITY', 401).
test_case('testsets/openbsd_netiquette_protocol.pl', 'openbsd_netiquette_protocol', 'OPENBSD_NETIQUETTE_PROTOCOL', 402).
test_case('testsets/optimization_fragility.pl', 'optimization_fragility', 'OPTIMIZATION_FRAGILITY', 403).
test_case('testsets/overfitting_to_frameworks.pl', 'overfitting_to_frameworks', 'OVERFITTING_TO_FRAMEWORKS', 404).
test_case('testsets/overton_window.pl', 'overton_interval', 'OVERTON_WINDOW', 405).
test_case('testsets/p_vs_np.pl', 'p_vs_np_interval', 'P_VS_NP', 406).
test_case('testsets/parable_fish_turtle.pl', 'parable_fish_turtle', 'PARABLE_FISH_TURTLE', 407).
test_case('testsets/pareto_principle.pl', 'pareto_principle', 'PARETO_PRINCIPLE', 408).
test_case('testsets/paris_municipal_reform_2026.pl', 'paris_municipal_reform_2026', 'PARIS_MUNICIPAL_REFORM_2026', 409).
test_case('testsets/parkinsons_law.pl', 'parkinson_interval', 'PARKINSONS_LAW', 410).
test_case('testsets/path_dependence_lock_in.pl', 'path_dependence_lock_in', 'PATH_DEPENDENCE_LOCK_IN', 411).
test_case('testsets/peano_curve_mapping.pl', 'peano_era', 'PEANO_CURVE_MAPPING', 412).
test_case('testsets/permissive_software_licensing.pl', 'permissive_software_licensing', 'PERMISSIVE_SOFTWARE_LICENSING', 413).
test_case('testsets/perovskite_self_etching.pl', 'perovskite_self_etching', 'PEROVSKITE_SELF_ETCHING', 414).
test_case('testsets/personalized_nutritional_arbitrage.pl', 'personalized_nutritional_arbitrage', 'PERSONALIZED_NUTRITIONAL_ARBITRAGE', 415).
test_case('testsets/peter_principle.pl', 'peter_principle', 'PETER_PRINCIPLE', 416).
test_case('testsets/planetary_boundaries.pl', 'planetary_boundaries', 'PLANETARY_BOUNDARIES', 417).
test_case('testsets/planetary_diet_constraint_2026.pl', 'planetary_diet_constraint_2026', 'PLANETARY_DIET_CONSTRAINT_2026', 418).
test_case('testsets/planning_fallacy.pl', 'planning_fallacy_interval', 'PLANNING_FALLACY', 419).
test_case('testsets/platform_cooperativism_governance.pl', 'platform_cooperativism_governance', 'PLATFORM_COOPERATIVISM_GOVERNANCE', 420).
test_case('testsets/platonic_coparenting_decoupling.pl', 'platonic_coparenting', 'PLATONIC_COPARENTING_DECOUPLING', 421).
test_case('testsets/poetic_verse_and_past.pl', 'poetic_verse_and_past', 'POETIC_VERSE_AND_PAST', 422).
test_case('testsets/poincare_conjucture.pl', 'poincare_era', 'POINCARE_CONJUCTURE', 423).
test_case('testsets/policy_lag_catastrophe.pl', 'policy_lag_catastrophe', 'POLICY_LAG_CATASTROPHE', 424).
test_case('testsets/politeness_face_negotiation.pl', 'politeness_face_negotiation', 'POLITENESS_FACE_NEGOTIATION', 425).
test_case('testsets/portugal_government_stability_ad.pl', 'portugal_ad_stability_2026', 'PORTUGAL_GOVERNMENT_STABILITY_AD', 426).
test_case('testsets/portugal_polarization_threshold_2026.pl', 'portugal_polarization_threshold_2026', 'PORTUGAL_POLARIZATION_THRESHOLD_2026', 427).
test_case('testsets/portuguese_presidential_term_limits.pl', 'portuguese_presidential_term_limits', 'PORTUGUESE_PRESIDENTIAL_TERM_LIMITS', 428).
test_case('testsets/postman_survival_protocol.pl', 'postman_survival_interval', 'POSTMAN_SURVIVAL_PROTOCOL', 429).
test_case('testsets/power_without_responsibility.pl', 'power_without_responsibility', 'POWER_WITHOUT_RESPONSIBILITY', 430).
test_case('testsets/prestige_signal_inflation.pl', 'prestige_signal_inflation', 'PRESTIGE_SIGNAL_INFLATION', 431).
test_case('testsets/price_signal_corruption.pl', 'price_signal_corruption', 'PRICE_SIGNAL_CORRUPTION', 432).
test_case('testsets/prime_number_theorem.pl', 'pnt_era', 'PRIME_NUMBER_THEOREM', 433).
test_case('testsets/prisoners_dilemma_equilibrium.pl', 'game_theory_era', 'PRISONERS_DILEMMA_EQUILIBRIUM', 434).
test_case('testsets/private_identity_integration.pl', 'private_identity_integration', 'PRIVATE_IDENTITY_INTEGRATION', 435).
test_case('testsets/procedural_compliance_theater.pl', 'procedural_compliance_theater', 'PROCEDURAL_COMPLIANCE_THEATER', 436).
test_case('testsets/procedural_legitimacy_decay.pl', 'procedural_legitimacy_decay', 'PROCEDURAL_LEGITIMACY_DECAY', 437).
test_case('testsets/proof_of_work_consensus.pl', 'proof_of_work_consensus', 'PROOF_OF_WORK_CONSENSUS', 438).
test_case('testsets/protocol_capture_tangled_rope.pl', 'protocol_capture_eee', 'PROTOCOL_CAPTURE_TANGLED_ROPE', 439).
test_case('testsets/protocol_drift_accumulation.pl', 'protocol_drift_accumulation', 'PROTOCOL_DRIFT_ACCUMULATION', 440).
test_case('testsets/public_domain_commons.pl', 'public_domain_commons', 'PUBLIC_DOMAIN_COMMONS', 441).
test_case('testsets/pythagorean_theorem_geometric_constancy.pl', 'pythagorean_era', 'PYTHAGOREAN_THEOREM_GEOMETRIC_CONSTANCY', 442).
test_case('testsets/qualified_immunity.pl', 'qi_interval', 'QUALIFIED_IMMUNITY', 443).
test_case('testsets/quantam_decryption_risk_2026.pl', 'quantum_decryption_risk_2026', 'QUANTAM_DECRYPTION_RISK_2026', 444).
test_case('testsets/quantum_entanglement_protocol.pl', 'interstellar_quantum_link', 'QUANTUM_ENTANGLEMENT_PROTOCOL', 445).
test_case('testsets/quantum_nonlocality_2026.pl', 'quantum_nonlocality_2026', 'QUANTUM_NONLOCALITY_2026', 446).
test_case('testsets/quellcrist_falconer_justice.pl', 'quellcrist_falconer_justice', 'QUELLCRIST_FALCONER_JUSTICE', 447).
test_case('testsets/quine_self_replication.pl', 'quine_era', 'QUINE_SELF_REPLICATION', 448).
test_case('testsets/qwerty_vs_dvorak.pl', 'qwerty_lockin_interval', 'QWERTY_VS_DVORAK', 449).
test_case('testsets/radiologic_diagnostic_threshold.pl', 'radiology_r7', 'RADIOLOGIC_DIAGNOSTIC_THRESHOLD', 450).
test_case('testsets/railway_gauge_standard.pl', 'railway_gauge_standard', 'RAILWAY_GAUGE_STANDARD', 451).
test_case('testsets/rational_inertia_trap.pl', 'rational_inertia_trap', 'RATIONAL_INERTIA_TRAP', 452).
test_case('testsets/recipe_scaling_ai.pl', 'recipe_scaling_ai', 'RECIPE_SCALING_AI', 453).
test_case('testsets/reciprocity_laws_math.pl', 'reciprocity_laws_math', 'RECIPROCITY_LAWS_MATH', 454).
test_case('testsets/regulatory_capture.pl', 'capture_interval', 'REGULATORY_CAPTURE', 455).
test_case('testsets/relativity_of_simultaneity.pl', 'relativity_of_simultaneity', 'RELATIVITY_OF_SIMULTANEITY', 456).
test_case('testsets/relativity_physical_invariance.pl', 'relativity_physical_invariance', 'RELATIVITY_PHYSICAL_INVARIANCE', 457).
test_case('testsets/rent_seeking_equilibrium.pl', 'rent_seeking_equilibrium', 'RENT_SEEKING_EQUILIBRIUM', 458).
test_case('testsets/reputational_cascade_failure.pl', 'reputational_cascade_failure', 'REPUTATIONAL_CASCADE_FAILURE', 459).
test_case('testsets/responsibility_dilution.pl', 'responsibility_dilution', 'RESPONSIBILITY_DILUTION', 460).
test_case('testsets/responsibility_without_power.pl', 'responsibility_without_power', 'RESPONSIBILITY_WITHOUT_POWER', 461).
test_case('testsets/rfc9293_interoperability.pl', 'tcp_rfc9293_interoperability', 'RFC9293_INTEROPERABILITY', 462).
test_case('testsets/rfc9293_state_machine.pl', 'rfc9293_state_machine', 'RFC9293_STATE_MACHINE', 463).
test_case('testsets/rices_theorem_undecidability.pl', 'rices_era', 'RICES_THEOREM_UNDECIDABILITY', 464).
test_case('testsets/risk_socialization_threshold.pl', 'risk_socialization_threshold', 'RISK_SOCIALIZATION_THRESHOLD', 465).
test_case('testsets/ritual_without_belief.pl', 'ritual_without_belief', 'RITUAL_WITHOUT_BELIEF', 466).
test_case('testsets/ritualistic_transition_scaffold.pl', 'ritual_transition_scaffold', 'RITUALISTIC_TRANSITION_SCAFFOLD', 467).
test_case('testsets/robustness_vs_efficiency_tradeoff.pl', 'robustness_vs_efficiency_tradeoff', 'ROBUSTNESS_VS_EFFICIENCY_TRADEOFF', 468).
test_case('testsets/rogers_commission_institutional_analysis.pl', 'challenger_post_mortem', 'ROGERS_COMMISSION_INSTITUTIONAL_ANALYSIS', 469).
test_case('testsets/rotation_seven_black_soil.pl', 'rotation_seven_black_soil', 'ROTATION_SEVEN_BLACK_SOIL', 470).
test_case('testsets/rotation_seven_isolation.pl', 'rotation_seven_isolation', 'ROTATION_SEVEN_ISOLATION', 471).
test_case('testsets/rotation_seven_kubo_ranking.pl', 'rotation_seven_kubo_ranking', 'ROTATION_SEVEN_KUBO_RANKING', 472).
test_case('testsets/rotmigration_decision_threshold.pl', 'migration_theory_review', 'ROTMIGRATION_DECISION_THRESHOLD', 473).
test_case('testsets/royal_navy_middle_east_withdrawal.pl', 'rn_withdrawal_cycle', 'ROYAL_NAVY_MIDDLE_EAST_WITHDRAWAL', 474).
test_case('testsets/rule_update_failure.pl', 'rule_update_failure', 'RULE_UPDATE_FAILURE', 475).
test_case('testsets/rules_based_international_order.pl', 'rules_based_international_order', 'RULES_BASED_INTERNATIONAL_ORDER', 476).
test_case('testsets/russells_paradox_self_reference.pl', 'russell_era', 'RUSSELLS_PARADOX_SELF_REFERENCE', 477).
test_case('testsets/russian_war_cannibalization.pl', 'russia_cannibalization_cycle', 'RUSSIAN_WAR_CANNIBALIZATION', 478).
test_case('testsets/s1_airbnb.pl', 'airbnb_ipo_era', 'S1_AIRBNB', 479).
test_case('testsets/s1_visa.pl', 'visa_ipo_window', 'S1_VISA', 480).
test_case('testsets/s1_visa_judgment_sharing_agreement.pl', 'visa_litigation_ringfencing', 'S1_VISA_JUDGMENT_SHARING_AGREEMENT', 481).
test_case('testsets/sadhu_integrity_protocol.pl', 'sadhu_integrity_protocol', 'SADHU_INTEGRITY_PROTOCOL', 482).
test_case('testsets/sapir_whorf_hypothesis.pl', 'sapir_whorf_interval', 'SAPIR_WHORF_HYPOTHESIS', 483).
test_case('testsets/sat_csp_complexity.pl', 'sat_csp_interval', 'SAT_CSP_COMPLEXITY', 484).
test_case('testsets/scurvy_maritime_extraction.pl', 'scurvy_maritime_interval', 'SCURVY_MARITIME_EXTRACTION', 485).
test_case('testsets/second_order_unintended_consequences.pl', 'second_order_unintended_consequences', 'SECOND_ORDER_UNINTENDED_CONSEQUENCES', 486).
test_case('testsets/self_surpassing_superman.pl', 'zarathustra_hazar', 'SELF_SURPASSING_SUPERMAN', 487).
test_case('testsets/semantic_attack_surface.pl', 'semantic_attack_surface', 'SEMANTIC_ATTACK_SURFACE', 488).
test_case('testsets/semantic_overload_friction.pl', 'semantic_overload_friction', 'SEMANTIC_OVERLOAD_FRICTION', 489).
test_case('testsets/shadow_pricing_failure.pl', 'shadow_pricing_failure', 'SHADOW_PRICING_FAILURE', 490).
test_case('testsets/shannon_entropy_limit.pl', 'shannon_entropy_limit', 'SHANNON_ENTROPY_LIMIT', 491).
test_case('testsets/shitty_feedback_handling.pl', 'shitty_feedback_handling', 'SHITTY_FEEDBACK_HANDLING', 492).
test_case('testsets/shobies_existential_commitment.pl', 'shobies_existential_commitment', 'SHOBIES_EXISTENTIAL_COMMITMENT', 493).
test_case('testsets/shock_propagation_asymmetry.pl', 'shock_propagation_asymmetry', 'SHOCK_PROPAGATION_ASYMMETRY', 494).
test_case('testsets/signal_without_control.pl', 'signal_without_control', 'SIGNAL_WITHOUT_CONTROL', 495).
test_case('testsets/silent_dependency_activation.pl', 'silent_dependency_activation', 'SILENT_DEPENDENCY_ACTIVATION', 496).
test_case('testsets/silicon_lexicon_overload.pl', 'silicon_lexicon_overload', 'SILICON_LEXICON_OVERLOAD', 497).
test_case('testsets/skills_based_hiring.pl', 'skills_based_hiring', 'SKILLS_BASED_HIRING', 498).
test_case('testsets/skolems_paradox.pl', 'skolems_paradox_interval', 'SKOLEMS_PARADOX', 499).
test_case('testsets/sleep_debt_externality.pl', 'sleep_debt_externality', 'SLEEP_DEBT_EXTERNALITY', 500).
test_case('testsets/slow_crisis_invisibility.pl', 'slow_crisis_invisibility', 'SLOW_CRISIS_INVISIBILITY', 501).
test_case('testsets/sludge_bureaucratic_friction.pl', 'sludge_bureaucratic_friction', 'SLUDGE_BUREAUCRATIC_FRICTION', 502).
test_case('testsets/smartphone_ubiquity.pl', 'smartphone_ubiquity', 'SMARTPHONE_UBIQUITY', 503).
test_case('testsets/social_credit_architecture.pl', 'scs_operational_2026', 'SOCIAL_CREDIT_ARCHITECTURE', 504).
test_case('testsets/social_loafing.pl', 'social_loafing_interval', 'SOCIAL_LOAFING', 505).
test_case('testsets/social_media_participation_threshold.pl', 'social_media_2025_cycle', 'SOCIAL_MEDIA_PARTICIPATION_THRESHOLD', 506).
test_case('testsets/social_narrative_casting.pl', 'social_narrative_casting', 'SOCIAL_NARRATIVE_CASTING', 507).
test_case('testsets/soft_authoritarian_drift.pl', 'soft_authoritarian_drift', 'SOFT_AUTHORITARIAN_DRIFT', 508).
test_case('testsets/solar_system_weirdness.pl', 'solar_system_weirdness', 'SOLAR_SYSTEM_WEIRDNESS', 509).
test_case('testsets/somatic_focusing_awareness.pl', 'somatic_focusing_awareness', 'SOMATIC_FOCUSING_AWARENESS', 510).
test_case('testsets/sorites_paradox.pl', 'sorites_interval', 'SORITES_PARADOX', 511).
test_case('testsets/south_china_sea_arbitration_2016_2026.pl', 'scs_legal_era', 'SOUTH_CHINA_SEA_ARBITRATION_2016_2026', 512).
test_case('testsets/spv_variations_us_cold.pl', 'spv_variations', 'SPV_VARIATIONS_US_COLD', 513).
test_case('testsets/square_cube_law.pl', 'square_cube_interval', 'SQUARE_CUBE_LAW', 514).
test_case('testsets/st_petersburg_paradox.pl', 'st_petersburg_era', 'ST_PETERSBURG_PARADOX', 515).
test_case('testsets/stable_marriage_coordination.pl', 'matching_theory_era', 'STABLE_MARRIAGE_COORDINATION', 516).
test_case('testsets/starwars_evolutionary_mutation.pl', 'galactic_selection_event', 'STARWARS_EVOLUTIONARY_MUTATION', 517).
test_case('testsets/statecraft_virtu.pl', 'statecraft_virtu_analysis', 'STATECRAFT_VIRTU', 518).
test_case('testsets/status_flattening_effect.pl', 'status_flattening_effect', 'STATUS_FLATTENING_EFFECT', 519).
test_case('testsets/steinmetz_valuation_asymmetry.pl', 'steinmetz_valuation_asymmetry', 'STEINMETZ_VALUATION_ASYMMETRY', 520).
test_case('testsets/stoic_logos_governance.pl', 'stoic_logos_governance', 'STOIC_LOGOS_GOVERNANCE', 521).
test_case('testsets/straight_coercion_2025.pl', 'strait_coercion_2025', 'STRAIGHT_COERCION_2025', 522).
test_case('testsets/strange_attractor_dynamics.pl', 'strange_attractor_dynamics', 'STRANGE_ATTRACTOR_DYNAMICS', 523).
test_case('testsets/structural_extraction_without_actor.pl', 'structural_extraction_without_actor', 'STRUCTURAL_EXTRACTION_WITHOUT_ACTOR', 524).
test_case('testsets/sts86_ascent_checklist.pl', 'sts86_ascent_checklist', 'STS86_ASCENT_CHECKLIST', 525).
test_case('testsets/sturgeons_law.pl', 'sturgeon_interval', 'STURGEONS_LAW', 526).
test_case('testsets/suanne_coup_of_peace.pl', 'suanne_coup_of_peace', 'SUANNE_COUP_OF_PEACE', 527).
test_case('testsets/suanne_face_restoration.pl', 'suanne_face_restoration', 'SUANNE_FACE_RESTORATION', 528).
test_case('testsets/sunk_cost_fallacy.pl', 'sunk_cost_interval', 'SUNK_COST_FALLACY', 529).
test_case('testsets/suslin_hypothesis_undecidability.pl', 'suslin_era', 'SUSLIN_HYPOTHESIS_UNDECIDABILITY', 530).
test_case('testsets/swift_legacy_piton.pl', 'swift_legacy_piton', 'SWIFT_LEGACY_PITON', 531).
test_case('testsets/swift_piton_snap.pl', 'swift_piton_snap', 'SWIFT_PITON_SNAP', 532).
test_case('testsets/sylow_theorems_group_theory.pl', 'sylow_era', 'SYLOW_THEOREMS_GROUP_THEORY', 533).
test_case('testsets/synthetic_data_feedback_loop.pl', 'synthetic_data_feedback_loop', 'SYNTHETIC_DATA_FEEDBACK_LOOP', 534).
test_case('testsets/systemic_blindspot.pl', 'systemic_blindspot', 'SYSTEMIC_BLINDSPOT', 535).
test_case('testsets/tail_risk_compression.pl', 'tail_risk_compression', 'TAIL_RISK_COMPRESSION', 536).
test_case('testsets/taiwan_existential_sovereignty.pl', 'taiwan_status_quo_cycle', 'TAIWAN_EXISTENTIAL_SOVEREIGNTY', 537).
test_case('testsets/taiwan_grand_bargain.pl', 'taiwan_grand_bargain', 'TAIWAN_GRAND_BARGAIN', 538).
test_case('testsets/taiwan_storm_2026.pl', 'taiwan_storm_2026', 'TAIWAN_STORM_2026', 539).
test_case('testsets/taiwan_strait_hegemony_shift.pl', 'hegemony_transition_window', 'TAIWAN_STRAIT_HEGEMONY_SHIFT', 540).
test_case('testsets/tarski_undefinability.pl', 'tarski_interval', 'TARSKI_UNDEFINABILITY', 541).
test_case('testsets/taxonomy_drift.pl', 'taxonomy_drift', 'TAXONOMY_DRIFT', 542).
test_case('testsets/teaching_horses_to_sing.pl', 'teaching_horses_to_sing_interval', 'TEACHING_HORSES_TO_SING', 543).
test_case('testsets/technocratic_overreach.pl', 'technocratic_overreach', 'TECHNOCRATIC_OVERREACH', 544).
test_case('testsets/technological_point_of_no_return.pl', 'technological_point_of_no_return', 'TECHNOLOGICAL_POINT_OF_NO_RETURN', 545).
test_case('testsets/technological_provenance_arbitrage.pl', 'technological_provenance_arbitrage', 'TECHNOLOGICAL_PROVENANCE_ARBITRAGE', 546).
test_case('testsets/tehran_water_bankruptcy.pl', 'tehran_water_bankruptcy', 'TEHRAN_WATER_BANKRUPTCY', 547).
test_case('testsets/temporal_resolution_mismatch.pl', 'temporal_resolution_mismatch', 'TEMPORAL_RESOLUTION_MISMATCH', 548).
test_case('testsets/temporal_scale_arbitrage.pl', 'temporal_scale_arbitrage', 'TEMPORAL_SCALE_ARBITRAGE', 549).
test_case('testsets/texas_hispanic_political_pivot.pl', 'tx_pivot_window_2026', 'TEXAS_HISPANIC_POLITICAL_PIVOT', 550).
test_case('testsets/thai_article_112_mountain.pl', 'thai_article_112_mountain', 'THAI_ARTICLE_112_MOUNTAIN', 551).
test_case('testsets/thai_senate_veto_2026.pl', 'thai_senate_veto_2026', 'THAI_SENATE_VETO_2026', 552).
test_case('testsets/thailand_2017_constitution.pl', 'thailand_2017_constitution', 'THAILAND_2017_CONSTITUTION', 553).
test_case('testsets/the_bacchae_madness_protocol.pl', 'theban_dionysian_conflict', 'THE_BACCHAE_MADNESS_PROTOCOL', 554).
test_case('testsets/the_calm_protocol_suppression.pl', 'the_calm_expedition_window', 'THE_CALM_PROTOCOL_SUPPRESSION', 555).
test_case('testsets/the_churn_systemic_upheaval.pl', 'the_churn_systemic_upheaval', 'THE_CHURN_SYSTEMIC_UPHEAVAL', 556).
test_case('testsets/the_novelty_gradient.pl', 'the_novelty_gradient', 'THE_NOVELTY_GRADIENT', 557).
test_case('testsets/the_stochastic_snare.pl', 'the_stochastic_snare', 'THE_STOCHASTIC_SNARE', 558).
test_case('testsets/the_wall_procedural_barrier.pl', 'the_wall_procedural_barrier', 'THE_WALL_PROCEDURAL_BARRIER', 559).
test_case('testsets/theory_of_visitors.pl', 'theory_of_visitors', 'THEORY_OF_VISITORS', 560).
test_case('testsets/thermodynamics_entropy.pl', 'thermodynamics_entropy_interval', 'THERMODYNAMICS_ENTROPY', 561).
test_case('testsets/three_body_unpredicability.pl', 'celestial_mechanics_era', 'THREE_BODY_UNPREDICABILITY', 562).
test_case('testsets/threshold_effect_miscalibration.pl', 'threshold_effect_miscalibration', 'THRESHOLD_EFFECT_MISCALIBRATION', 563).
test_case('testsets/too_big_to_manage.pl', 'too_big_to_manage', 'TOO_BIG_TO_MANAGE', 564).
test_case('testsets/tool_use_delegation_risk.pl', 'tool_use_delegation_risk', 'TOOL_USE_DELEGATION_RISK', 565).
test_case('testsets/toxic_social_infection.pl', 'toxic_social_infection_interval', 'TOXIC_SOCIAL_INFECTION', 566).
test_case('testsets/tractarian_logic_limit.pl', 'tractarian_logic_limit', 'TRACTARIAN_LOGIC_LIMIT', 567).
test_case('testsets/trade_secret_law.pl', 'trade_secret_law', 'TRADE_SECRET_LAW', 568).
test_case('testsets/tragedy_of_the_commons.pl', 'tragedy_of_the_commons', 'TRAGEDY_OF_THE_COMMONS', 569).
test_case('testsets/transformer_self_attention.pl', 'transformer_self_attention', 'TRANSFORMER_SELF_ATTENTION', 570).
test_case('testsets/transient_event_detection.pl', 'transient_event_detection', 'TRANSIENT_EVENT_DETECTION', 571).
test_case('testsets/transitional_utility_bridge.pl', 'transitional_utility_bridge', 'TRANSITIONAL_UTILITY_BRIDGE', 572).
test_case('testsets/traveling_salesperson_problem.pl', 'traveling_salesperson_problem', 'TRAVELING_SALESPERSON_PROBLEM', 573).
test_case('testsets/trojan_war_spoils.pl', 'trojan_collapse_interval', 'TROJAN_WAR_SPOILS', 574).
test_case('testsets/trump_making_china_great_2026.pl', 'post_trump_return', 'TRUMP_MAKING_CHINA_GREAT_2026', 575).
test_case('testsets/trumps_second_term_authoritarianism_2026.pl', 'trump_ii_year_one', 'TRUMPS_SECOND_TERM_AUTHORITARIANISM_2026', 576).
test_case('testsets/truth_by_repetition_effect.pl', 'truth_by_repetition_effect', 'TRUTH_BY_REPETITION_EFFECT', 577).
test_case('testsets/udhr_1946.pl', 'un_era', 'UDHR_1946', 578).
test_case('testsets/ulysses_chp01.pl', 'telemachus_morning', 'ULYSSES_CHP01', 579).
test_case('testsets/ulysses_chp02.pl', 'nestor_afternoon', 'ULYSSES_CHP02', 580).
test_case('testsets/ulysses_chp03.pl', 'proteus_strand_walk', 'ULYSSES_CHP03', 581).
test_case('testsets/ulysses_chp04.pl', 'bloom_kosher_transgression', 'ULYSSES_CHP04', 582).
test_case('testsets/ulysses_chp05.pl', 'bloom_secret_correspondence', 'ULYSSES_CHP05', 583).
test_case('testsets/ulysses_chp06.pl', 'bloom_exclusion_interval', 'ULYSSES_CHP06', 584).
test_case('testsets/ulysses_chp07.pl', 'bloom_aeolus_interval', 'ULYSSES_CHP07', 585).
test_case('testsets/ulysses_chp08.pl', 'lestrygonian_metabolism_chp8_interval', 'ULYSSES_CHP08', 586).
test_case('testsets/ulysses_chp09.pl', 'stephen_shakespeare_ghost', 'ULYSSES_CHP09', 587).
test_case('testsets/ulysses_chp10.pl', 'the_viceregal_cavalcade', 'ULYSSES_CHP10', 588).
test_case('testsets/ulysses_chp11.pl', 'bloom_sirens_interval', 'ULYSSES_CHP11', 589).
test_case('testsets/ulysses_chp12.pl', 'bloom_exclusion_id', 'ULYSSES_CHP12', 590).
test_case('testsets/ulysses_chp13.pl', 'gerty_bloom_interval', 'ULYSSES_CHP13', 591).
test_case('testsets/ulysses_chp14.pl', 'gestation_wombfruit_id', 'ULYSSES_CHP14', 592).
test_case('testsets/ulysses_chp15.pl', 'nighttown_vigil_id', 'ULYSSES_CHP15', 593).
test_case('testsets/ulysses_chp16.pl', 'bloom_samaritan_id', 'ULYSSES_CHP16', 594).
test_case('testsets/ulysses_chp17.pl', 'bloom_ithaca_interval', 'ULYSSES_CHP17', 595).
test_case('testsets/ulysses_chp18.pl', 'molly_affirmation_id', 'ULYSSES_CHP18', 596).
test_case('testsets/unclos_2026.pl', 'unclos_era', 'UNCLOS_2026', 597).
test_case('testsets/union_protection_underperformance.pl', 'labor_management_conflict_r1', 'UNION_PROTECTION_UNDERPERFORMANCE', 598).
test_case('testsets/universal_mathematics_communication.pl', 'scientific_consensus_period', 'UNIVERSAL_MATHEMATICS_COMMUNICATION', 599).
test_case('testsets/us_congress_2026_midterms.pl', 'gerrymandering_incumbency_2026', 'US_CONGRESS_2026_MIDTERMS', 600).
test_case('testsets/us_hydrological_debt.pl', 'us_hydrological_debt', 'US_HYDROLOGICAL_DEBT', 601).
test_case('testsets/us_suburban_zoning_2025.pl', 'us_suburban_zoning_2025', 'US_SUBURBAN_ZONING_2025', 602).
test_case('testsets/us_two_party_duopoly.pl', 'us_two_party_duopoly', 'US_TWO_PARTY_DUOPOLY', 603).
test_case('testsets/utopia_apocalypse_fragility.pl', 'utopia_apocalypse_fragility', 'UTOPIA_APOCALYPSE_FRAGILITY', 604).
test_case('testsets/value_alignment_drift.pl', 'value_alignment_drift', 'VALUE_ALIGNMENT_DRIFT', 605).
test_case('testsets/value_extraction_plateau.pl', 'value_extraction_plateau', 'VALUE_EXTRACTION_PLATEAU', 606).
test_case('testsets/value_learning_instability.pl', 'value_learning_instability', 'VALUE_LEARNING_INSTABILITY', 607).
test_case('testsets/van_der_waerden_theorem.pl', 'van_der_waerden_interval', 'VAN_DER_WAERDEN_THEOREM', 608).
test_case('testsets/viral_transmission_rates.pl', 'viral_transmission_rates', 'VIRAL_TRANSMISSION_RATES', 609).
test_case('testsets/visibility_bias_governance.pl', 'visibility_bias_governance', 'VISIBILITY_BIAS_GOVERNANCE', 610).
test_case('testsets/weber_fechner_law.pl', 'weber_fechner_law', 'WEBER_FECHNER_LAW', 611).
test_case('testsets/whitehead_problem_undecidability.pl', 'whitehead_era', 'WHITEHEAD_PROBLEM_UNDECIDABILITY', 612).
test_case('testsets/wikipedia_crowdsourcing_2026.pl', 'wikipedia_crowdsourcing_2026', 'WIKIPEDIA_CROWDSOURCING_2026', 613).
test_case('testsets/wikipedia_notability_requirement_2026.pl', 'wikipedia_notability_requirement_2026', 'WIKIPEDIA_NOTABILITY_REQUIREMENT_2026', 614).
test_case('testsets/winners_curse.pl', 'winners_curse', 'WINNERS_CURSE', 615).
test_case('testsets/xi_mao_ideological_centralization.pl', 'xi_mao_ideological_centralization', 'XI_MAO_IDEOLOGICAL_CENTRALIZATION', 616).
test_case('testsets/zipfs_law.pl', 'zipfs_law', 'ZIPFS_LAW', 617).

% --- Test Suite Runner ---
run_dynamic_suite :-
    retractall(test_passed(_)),
    retractall(test_failed(_, _, _)),
    writeln('--- STARTING DYNAMIC VALIDATION ---'),
    forall(test_case(Path, ID, Label, N), run_single_test(Path, ID, Label, N)),
    count_and_report,
    % Call validate_all directly from data_validation module
    data_validation:validate_all.

% --- Single Test Executor ---
run_single_test(Path, ID, _Label, N) :-
    format('~n[~w] EXECUTING: ~w~n', [N, Path]),
    catch_with_backtrace(
        ( load_and_run(Path, ID) ->
            assertz(test_passed(Path)),
            format('[PASS] ~w~n', [Path])
        ;   assertz(test_failed(Path, audit_failed, 'load_and_run returned false')),
            format('[AUDIT FAIL] ~w~n', [Path])
        ),
        E,
        (   assertz(test_failed(Path, exception, E)),
            format('[FAIL] Exception for ~w: ~w~n', [Path, E]),
            print_prolog_backtrace(current_output, E)
        )
    ),
    report_generator:generate_llm_feedback(ID).

% --- Result Counter & Reporter ---
count_and_report :-
    findall(P, test_passed(P), Ps), length(Ps, PC),
    findall(F, test_failed(F,_,_), Fs), length(Fs, FC),
    writeln(''),
    writeln('=================================================='),
    writeln('           TEST SUITE SUMMARY'),
    writeln('=================================================='),
    format('Passed: ~w~n', [PC]),
    format('Failed: ~w~n', [FC]),
    (FC > 0 -> report_failures ; true),
    writeln('==================================================').

report_failures :-
    writeln('--- FAILED TESTS ---'),
    forall(test_failed(Path, Type, Detail),
           format('~n  - [~w] ~w~n    Reason: ~w~n', [Type, Path, Detail])).

